export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
export const FETCH_SEARCH_RESULT_SUCCESS = 'FETCH_SEARCH_RESULT_SUCCESS';
export const FETCH_SEARCH_RESULT_FAILURE = 'FETCH_SEARCH_RESULT_FAILURE';

export const FETCH_PEOPLE = 'FETCH_PEOPLE';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';

export const FETCH_PERSON = 'FETCH_PERSON';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';

export const RESET_STATE = 'RESET_STATE';

export const SET_USER_CREDS = 'SET_USER_CREDS';
export const LOG_OUT = 'LOG_OUT';

export const EVENT_ERROR = 'EVENT_ERROR';
export const EVENT_SUCCESS = 'EVENT_SUCCESS';

export const TRACK_EMAIL = 'TRACK_EMAIL';
export const TRACK_EMAIL_SUCCESS = 'TRACK_EMAIL_SUCCESS';
export const TRACK_EMAIL_FAILURE = 'TRACK_EMAIL_FAILURE';

export const RESET_PERSON = 'RESET_PERSON';
